### ISSUE TITLE
Xcode 16 build failure

### ISSUE THREAD

**Issue by yannisalexiou** [amosavian/JWSETKit#14]
Is it possible to update the library version with the latest commit from main?

Version 0.21.0 failed to build with the following error:
`Thrown expression type 'any Error' cannot be converted to error type 'Never'`
This occurred in the `KeyExporter.swift` file, specifically in the following declaration:
`var keyCurve: JSONWebKeyCurve?`

![Screenshot 2024-09-16 at 10 49 25 AM](https://github.com/user-attachments/assets/e39b2dff-1d7f-47b5-81b9-e2ba3d7553b2)

If I get the last commit from main branch everything plays like a charm

Xcode Version: `16.0 (16A242)`

**Comment by amosavian** [comment]
Hi @yannisalexiou ,
This is fixed in [JESETKit 0.21.1](https://github.com/amosavian/JWSETKit/releases/tag/0.21.1)

**Comment by yannisalexiou** [comment]
Thank you @amosavian 🚀
