### ISSUE TITLE
POV: More use of enum

### ISSUE THREAD

**Issue by MojtabaHs** [amosavian/JWSETKit#3]
Is there a reason that causes you to not use `enum` for types like `JSONWebKeyCurve` and `JSONWebKeyType`?
Using `enum` can bring more compiler safety for cases like `keyLengthInBytes` and `verifySignature`.

**Comment by amosavian** [comment]
After maturation of APIs and interactions, I intend to make it more expandable with defining/injecting custom algorithms.
