### ISSUE TITLE
Wrong alg value

### ISSUE THREAD

**Issue by leftkaramolegos** [amosavian/JWSETKit#9]
I'm running this code

    let jwe = try! JSONWebEncryption(
        content: Data("Live long and prosper.".utf8),
        keyEncryptingAlgorithm: .direct,
        keyEncryptionKey: nil,
        contentEncryptionAlgorithm: .aesEncryptionGCM256,
        contentEncryptionKey: kek
and the header outcome is {"typ":"JWE","alg":"direct","enc":"A256GCM"}
but the correct value for alg is "dir" (at least for my c# backend)

**Comment by amosavian** [comment]
Please use version 0.16.0. This bug is fixed now.
